name: Build and Test

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches: [main, early-access]
  push:
    branches: [main, early-access]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CACHE_KEY: "${{ github.ref }}-${{ github.run_id }}-${{ github.run_attempt }}"

jobs:
  test:
    strategy:
      matrix:
        node: [ 20, 22 ]
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with npm caching
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Examples
        run: turbo run build --filter="{./examples/*}"